version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql_db_container
    ports:
      - "3306:3306"
    env_file:
      - mysql.env
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
